name: Continuous Deployment
on:
  push:
    branches:
    - source
  workflow_dispatch:

jobs:
  build:
    name: Build static page
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    - id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install PHP dependencies
      run: composer install --prefer-dist --no-progress
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install asset dependencies
      run: |
        npm ci
        npm run production
    - name: Publish static files
      uses: actions/upload-pages-artifact@v1
      with:
        path: build_production/

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - id: deployment
      uses: actions/deploy-pages@v2
